# Generated by Django 6.0.3 on 2026-03-25 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип артефакта')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Сохранность')),
            ],
        ),
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название эпохи')),
                ('start_year', models.IntegerField(blank=True, null=True, verbose_name='Год начала')),
                ('end_year', models.IntegerField(blank=True, null=True, verbose_name='Год окончания')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Материал')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название памятника')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('coordinates_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('coordinates_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('discovered_year', models.IntegerField(blank=True, null=True, verbose_name='Год открытия')),
                ('status', models.CharField(choices=[('active', 'Активный раскоп'), ('conservation', 'Консервация'), ('finished', 'Исследования завершены')], default='active', max_length=20, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название культуры')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('era', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.era', verbose_name='Эпоха')),
            ],
        ),
        migrations.CreateModel(
            name='Find',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_number', models.CharField(max_length=50, unique=True, verbose_name='Инвентарный номер')),
                ('title', models.CharField(max_length=200, verbose_name='Название находки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('discovery_date', models.DateField(blank=True, null=True, verbose_name='Дата обнаружения')),
                ('excavation_area', models.CharField(blank=True, max_length=50, verbose_name='Участок/Раскоп')),
                ('square', models.CharField(blank=True, max_length=50, verbose_name='Квадрат')),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Глубина (м)')),
                ('layer', models.CharField(blank=True, max_length=50, verbose_name='Слой/Ярус')),
                ('dimensions', models.CharField(blank=True, max_length=100, verbose_name='Размеры (ДxШxВ)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Вес (г)')),
                ('condition_notes', models.TextField(blank=True, verbose_name='Заметки о сохранности')),
                ('status', models.CharField(choices=[('field', 'В полевой лаборатории'), ('storage', 'В фондах'), ('exhibition', 'На экспозиции'), ('restoration', 'На реставрации')], default='field', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('artifact_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.artifacttype', verbose_name='Тип')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
                ('condition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.condition', verbose_name='Состояние')),
                ('culture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.culture', verbose_name='Культура')),
                ('era', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.era', verbose_name='Эпоха')),
                ('materials', models.ManyToManyField(to='catalog.material', verbose_name='Материалы')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finds', to='catalog.site', verbose_name='Памятник')),
            ],
        ),
        migrations.CreateModel(
            name='FindImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='finds_images/', verbose_name='Изображение')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание фото')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('order_index', models.IntegerField(default=0, verbose_name='Порядок вывода')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('find', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.find', verbose_name='Находка')),
            ],
        ),
    ]
