# Generated by Django 6.0.3 on 2026-04-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifacttype',
            name='category',
        ),
        migrations.AlterField(
            model_name='artifacttype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Категория (Тип)'),
        ),
    ]
