# Generated by Django 6.0.3 on 2026-05-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_artifacttype_category_alter_artifacttype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='find',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='finds_images/', verbose_name='Фото'),
        ),
    ]
