# Generated by Django 6.0.3 on 2026-06-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_find_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='find',
            name='site',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Раскоп (место)'),
        ),
        migrations.RemoveField(
            model_name='find',
            name='inv_number',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
